### PR TITLE
Added UI Settings for top bar font weight

### PR DESCRIPTION
**Pull request by bhavesh100**

### CODE REVIEW

**Review by lorenzovngl — CHANGES_REQUESTED** [review]
I built and ran the app with these changes and... thinking about it... a separate activity for UI settings is not the best idea considering the limited number of settings.

I think the best choice is to put all in the SettingsActivity, separating behavioral settings from appearance settings using two headers:

**Behavior**
[Date format]
[Notification time]
**Appearance**
[Theme]
[Dynamic colors]
[Top app bar font weight]

**Review by lorenzovngl — CHANGES_REQUESTED** [review]
Perfect, only one thing left. There is this little bug when you switch between the options, but I think you can fix it easily.

https://github.com/lorenzovngl/FoodExpirationDates/assets/13767301/b582231a-84b4-442a-8fb6-70911855d0e2

**Comment by bhavesh100** [comment]
I don't know why this bug is coming. I just interchanged the if conditions the bug went away.

**Review by lorenzovngl — APPROVED** [review]
Look awesome, thank you!

**Pull request merged**
