### PR TITLE
Changing order of buttons in Bottom App Bar

### PR DESCRIPTION
**Pull request by anuragkanojiya1**
## Related Issue

Closes: #187 

## Description

Changed the order of buttons in the Bottom App Bar of FoodExpirationDates project.

### CODE REVIEW

**Review by lorenzovngl — CHANGES_REQUESTED** [review]
Hello and thank you for your contribution!
I reviewed your changes. They are ok but are not enoght to accept the work as finished.
As you can see in the video below, the behavior is not good.

https://github.com/user-attachments/assets/39dacdb2-66f2-4f74-af03-1d52b17784f9

Take a look at this code: you need to adapt it to the new order.
_Also, please remember to test your changes before submitting pull requests._

https://github.com/lorenzovngl/FoodExpirationDates/blob/fb5c30220902282f86eec26cffb41de5ae3b58ce/app/src/main/java/com/lorenzovainigli/foodexpirationdates/view/composable/MyBottomAppBar.kt#L52-L56

And please remove these files from your commit:
image

If you have troubles with something, I can help you 🙂

**Comment by anuragkanojiya1** [comment]
> Hello and thank you for your contribution! I reviewed your changes. They are ok but are not enoght to accept the work as finished. As you can see in the video below, the behavior is not good.
> 
>  Registrazione.dello.schermo.2024-10-05.162559.mp4 
> Take a look at this code: you need to adapt it to the new order. _Also, please remember to test your changes before submitting pull requests._
> 
> https://github.com/lorenzovngl/FoodExpirationDates/blob/fb5c30220902282f86eec26cffb41de5ae3b58ce/app/src/main/java/com/lorenzovainigli/foodexpirationdates/view/composable/MyBottomAppBar.kt#L52-L56
> 
> And please remove these files from your commit: image
> 
> If you have troubles with something, I can help you 🙂

Okay sure, going to work on it now.

**Comment by anuragkanojiya1** [comment]
Task is Done.

You can check it out in this video below : 

https://github.com/user-attachments/assets/cf4612ce-7ade-4a39-bd95-4600b249cb77

**Review by lorenzovngl — APPROVED** [review]

**Comment by lorenzovngl** [comment]
All good! Thank you for your contribution! 😁🎉

**Pull request merged**
