### PR TITLE
Changed dark theme switch to radio buttons

### PR DESCRIPTION
**Pull request by bhavesh100**
Change the Dark theme switch to a radio button. On and off is working fine but system is working only in setting activity.

### CODE REVIEW

**Comment by lorenzovngl** [comment]
Good, there are parts that need to be improved but it's a good starting point.
Don't worry about the persistency of the data, I have the changes to save these states in the shared preferences, but I will commit them after the merge of this pull request.

Let's focus on the UI, my idea is the following:

image

Could you implement this, please? You can use `Button` for the option checked and `OutlinedButton` for the other options.

**Review by lorenzovngl — CHANGES_REQUESTED** [review]
Good, there are parts that need to be improved but it's a good starting point.
Don't worry about the persistency of the data, I have the changes to save these states in the shared preferences, but I will commit them after the merge of this pull request.

Let's focus on the UI, my idea is the following:

image

Could you implement this, please? You can use `Button` for the option checked and `OutlinedButton` for the other options.

**Comment by bhavesh100** [comment]
OK 👍 I will implement this

**Comment by bhavesh100** [comment]
I changed On and off to Dark and Light. And it looks good. 
IMG_20230608_132658

**Comment by lorenzovngl** [comment]
Closed because this PR has been replaced by #33

**Pull request closed without merging**
