### PR TITLE
Made Asked Changes for Replace Accompanist System UI Controller with Edge-to-Edge

### PR DESCRIPTION
**Pull request by AdityaKumdale**
Fixed the bug and deleted commeted and unnecessary code. Although I made changes you asked, I still think we may need implementation("androidx.activity:activity-compose:1.8.0-alpha07")  despite having, implementation(libs.activity.compose). Please tell if my pr is working out.

### CODE REVIEW

**Review by lorenzovngl — CHANGES_REQUESTED** [review]
Yes, the current version of `activity-compose` in the project (`1.7.2`) does not contain the functions that we need.
To solve this issue you can update the version of `activity-compose` here:

https://github.com/lorenzovngl/FoodExpirationDates/blob/d2f1b336ab39f4f6f6ea2343d2ce5371fde964e2/gradle/libs.versions.toml#L3

You can put version `1.8.0` since it is a stable version and [it has been released on October 4](https://developer.android.com/jetpack/androidx/releases/activity#1.8.0).

This project uses Gradle version catalogs, check out the [official documentation](https://developer.android.com/build/migrate-to-catalogs) if you don't know how it works.

Also, the bug I reported in the previous pull request seems to be solved.

**Comment by AdityaKumdale** [comment]
Thanks will fix that now

**Comment by AdityaKumdale** [comment]
Made Final changes with above commit

**Review by lorenzovngl — APPROVED** [review]

**Comment by lorenzovngl** [comment]
Thank you so much and welcome among the contributors! 🎉

**Pull request merged**
